# This file was generated by GoReleaser. DO NOT EDIT.
cask "iacbom" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "91197177ff4eee313e6695fb1a1be5f42b5c1455de0bf796764f63bb917f0c78"
      url "https://github.com/ojarosch/iacbom/releases/download/v#{version}/iacbom_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/ojarosch/iacbom"
    end
    on_intel do
      sha256 "ec00c6892f5a6e60f9755404e62dc2eb77e57668bd94a1142372ec140b5a17a7"
      url "https://github.com/ojarosch/iacbom/releases/download/v#{version}/iacbom_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/ojarosch/iacbom"
    end
  end
  on_linux do
    on_arm do
      sha256 "fbba4352873c18fcb1737661c931e7df9429bce754709b4ea686dbcb791569c3"
      url "https://github.com/ojarosch/iacbom/releases/download/v#{version}/iacbom_#{version}_linux_arm64.tar.gz",
        verified: "github.com/ojarosch/iacbom"
    end
    on_intel do
      sha256 "46ec9fb10f53da59e1cce3f4db68d4e41a3e194e47c39a5f740a571a7cbadafb"
      url "https://github.com/ojarosch/iacbom/releases/download/v#{version}/iacbom_#{version}_linux_amd64.tar.gz",
        verified: "github.com/ojarosch/iacbom"
    end
  end

  name "iacbom"
  desc "Bill of Materials for Terraform and OpenTofu repositories"
  homepage "https://github.com/ojarosch/iacbom"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "iacbom"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/iacbom"]
    end
  end

  # No zap stanza required
end
