# This file was generated by GoReleaser. DO NOT EDIT.
cask "iacbom" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "7b54fe4ef847791dc17c0fd969e707647c0f10c073b0c3890d35714c8d5436df"
      url "https://github.com/ojarosch/iacbom/releases/download/v#{version}/iacbom_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/ojarosch/iacbom"
    end
    on_intel do
      sha256 "02459eb1fcb2cab2fb7c7dd48148706e8185fb8784a49c101badcd1d2a93133e"
      url "https://github.com/ojarosch/iacbom/releases/download/v#{version}/iacbom_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/ojarosch/iacbom"
    end
  end
  on_linux do
    on_arm do
      sha256 "7e2df1e18dd81bc4ed13468d142eb6af71ea0ebc8822d1fd45b638d17b52bab8"
      url "https://github.com/ojarosch/iacbom/releases/download/v#{version}/iacbom_#{version}_linux_arm64.tar.gz",
        verified: "github.com/ojarosch/iacbom"
    end
    on_intel do
      sha256 "05322e55d8e00fc45a82758922d2ec789e09e6a904919bc389d6c6192b8a214c"
      url "https://github.com/ojarosch/iacbom/releases/download/v#{version}/iacbom_#{version}_linux_amd64.tar.gz",
        verified: "github.com/ojarosch/iacbom"
    end
  end

  name "iacbom"
  desc "Bill of Materials for Terraform and OpenTofu repositories"
  homepage "https://github.com/ojarosch/iacbom"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "iacbom"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/iacbom"]
    end
  end

  # No zap stanza required
end
