# This file was generated by GoReleaser. DO NOT EDIT.
cask "planlens" do
  version "0.2.1"

  on_macos do
    on_arm do
      sha256 "466df233efbe54901395ea8462591d7dbeb2693231bc0d72ef446d8f120d12cc"
      url "https://github.com/ojarosch/planlens/releases/download/v#{version}/planlens_#{version}_Darwin_aarch64.tar.gz",
        verified: "github.com/ojarosch/planlens"
    end
    on_intel do
      sha256 "4a8975aaa566336bdbfca343e09d1b1cf4199a780cdb48af5375dec78bab48e7"
      url "https://github.com/ojarosch/planlens/releases/download/v#{version}/planlens_#{version}_Darwin_x86_64.tar.gz",
        verified: "github.com/ojarosch/planlens"
    end
  end
  on_linux do
    on_arm do
      sha256 "4012d056dee39c01d364435ea3ebe164acf977c63aec7a71f4fcb16de4019fec"
      url "https://github.com/ojarosch/planlens/releases/download/v#{version}/planlens_#{version}_Linux_aarch64.tar.gz",
        verified: "github.com/ojarosch/planlens"
    end
    on_intel do
      sha256 "dbab382c67123fc11d0353a9390a870a09ca4adcd5cb74fe68831f89d27b9ad1"
      url "https://github.com/ojarosch/planlens/releases/download/v#{version}/planlens_#{version}_Linux_x86_64.tar.gz",
        verified: "github.com/ojarosch/planlens"
    end
  end

  name "planlens"
  desc "Reviewer-oriented semantic diff for Terraform/OpenTofu plans"
  homepage "https://github.com/ojarosch/planlens"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "planlens"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/planlens"]
    end
  end

  # No zap stanza required
end
