# This file was generated by GoReleaser. DO NOT EDIT.
cask "planlens" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "f5010e0d30f0840b9a44136ff4810879b7293c653265af4d3f57f0f7e15cf1ad"
      url "https://github.com/ojarosch/planlens/releases/download/v#{version}/planlens_#{version}_Darwin_aarch64.tar.gz"
    end
    on_intel do
      sha256 "5860f6fa38cc03a15ee18fa4ab603d9b67f14526bdf0a09e23827a2c7cd720c5"
      url "https://github.com/ojarosch/planlens/releases/download/v#{version}/planlens_#{version}_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "496e552f7b54e9b05fab6a62e00bcd90ea5a1fb64a9042aa77f7095e8d51b32c"
      url "https://github.com/ojarosch/planlens/releases/download/v#{version}/planlens_#{version}_Linux_aarch64.tar.gz"
    end
    on_intel do
      sha256 "d29ccd511aaccfb0df13f8f250ece43c1345f584ea6f0ba3d8dea77031b9d5ac"
      url "https://github.com/ojarosch/planlens/releases/download/v#{version}/planlens_#{version}_Linux_x86_64.tar.gz"
    end
  end

  name "planlens"
  desc "Reviewer-oriented semantic diff for Terraform/OpenTofu plans"
  homepage "https://github.com/ojarosch/planlens"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "planlens"

  # No zap stanza required
end
