# This file was generated by GoReleaser. DO NOT EDIT.
cask "tfdoctor" do
  version "0.1.2"

  on_macos do
    on_arm do
      sha256 "30f9d02b5f789893e6fccfc788d17bc59cea3d103be4bffa311b384e2f5db673"
      url "https://github.com/ojarosch/tfdoctor/releases/download/v#{version}/tfdoctor_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/ojarosch/tfdoctor"
    end
    on_intel do
      sha256 "6a1963ed3b89aa1b4dde02e999a63aad232a4ffac1d8a78c7e914b4d7fd07716"
      url "https://github.com/ojarosch/tfdoctor/releases/download/v#{version}/tfdoctor_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/ojarosch/tfdoctor"
    end
  end
  on_linux do
    on_arm do
      sha256 "4c33390498500ca6f1925c3b19b87b1914bbeae2fc49833bcfe715a8d146f9e9"
      url "https://github.com/ojarosch/tfdoctor/releases/download/v#{version}/tfdoctor_#{version}_linux_arm64.tar.gz",
        verified: "github.com/ojarosch/tfdoctor"
    end
    on_intel do
      sha256 "3d509fa940a20e3d9a57e3d781a4b5e5b24895a5490cb0678874a2445e11a6ab"
      url "https://github.com/ojarosch/tfdoctor/releases/download/v#{version}/tfdoctor_#{version}_linux_amd64.tar.gz",
        verified: "github.com/ojarosch/tfdoctor"
    end
  end

  name "tfdoctor"
  desc "Check the engineering hygiene of a Terraform/OpenTofu repository"
  homepage "https://github.com/ojarosch/tfdoctor"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tfdoctor"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tfdoctor"]
    end
  end

  # No zap stanza required
end
