# This file was generated by GoReleaser. DO NOT EDIT.
cask "tfdoctor" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "f659db4c308c8c242aaedaf9952c0b975df84818c8941496ce57656130dac073"
      url "https://github.com/ojarosch/tfdoctor/releases/download/v#{version}/tfdoctor_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/ojarosch/tfdoctor"
    end
    on_intel do
      sha256 "19cd4669c59e1fe9c2d444d576c10e59c43c0326e004e2348e479a4723e5b054"
      url "https://github.com/ojarosch/tfdoctor/releases/download/v#{version}/tfdoctor_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/ojarosch/tfdoctor"
    end
  end
  on_linux do
    on_arm do
      sha256 "66c3196e2f5712c829ba547271e73fb3bf4e1ff65cda82ddd52b13679b83e495"
      url "https://github.com/ojarosch/tfdoctor/releases/download/v#{version}/tfdoctor_#{version}_linux_arm64.tar.gz",
        verified: "github.com/ojarosch/tfdoctor"
    end
    on_intel do
      sha256 "1fe818a96d1d688bb23e3618a5713c5e0939bcd38995f604f7040f493f870b89"
      url "https://github.com/ojarosch/tfdoctor/releases/download/v#{version}/tfdoctor_#{version}_linux_amd64.tar.gz",
        verified: "github.com/ojarosch/tfdoctor"
    end
  end

  name "tfdoctor"
  desc "Check the engineering hygiene of a Terraform/OpenTofu repository"
  homepage "https://github.com/ojarosch/tfdoctor"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tfdoctor"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tfdoctor"]
    end
  end

  # No zap stanza required
end
