# This file was generated by GoReleaser. DO NOT EDIT.
cask "tfdoctor" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "71b86405f9f97fb89548c1cc2625775f6f1c5540a3d5c4a74bb5188e83033fd9"
      url "https://github.com/ojarosch/tfdoctor/releases/download/v#{version}/tfdoctor_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/ojarosch/tfdoctor"
    end
    on_intel do
      sha256 "84d263c543c6b768883741259015c56570e9f6074940be56450f1b53af3f0fa0"
      url "https://github.com/ojarosch/tfdoctor/releases/download/v#{version}/tfdoctor_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/ojarosch/tfdoctor"
    end
  end
  on_linux do
    on_arm do
      sha256 "d72ca6be406e3b1f4be4636b404ebec7ceecfa79aae7477875911d242323894d"
      url "https://github.com/ojarosch/tfdoctor/releases/download/v#{version}/tfdoctor_#{version}_linux_arm64.tar.gz",
        verified: "github.com/ojarosch/tfdoctor"
    end
    on_intel do
      sha256 "75e27a74c6542b1ae1d3368a839c12fa04ce8de4bd86775e69fee900347407a5"
      url "https://github.com/ojarosch/tfdoctor/releases/download/v#{version}/tfdoctor_#{version}_linux_amd64.tar.gz",
        verified: "github.com/ojarosch/tfdoctor"
    end
  end

  name "tfdoctor"
  desc "Check the engineering hygiene of a Terraform/OpenTofu repository"
  homepage "https://github.com/ojarosch/tfdoctor"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tfdoctor"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tfdoctor"]
    end
  end

  # No zap stanza required
end
