# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Iacbom < Formula
  desc "Bill of Materials for Terraform and OpenTofu repositories"
  homepage "https://github.com/ojarosch/iacbom"
  version "0.1.5"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ojarosch/iacbom/releases/download/v0.1.5/iacbom_0.1.5_darwin_amd64.tar.gz"
      sha256 "8a0554f2fc936e407cf19f720f15b7269a00f672b617e257d666e6ef75d1db14"

      define_method(:install) do
        bin.install "iacbom"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ojarosch/iacbom/releases/download/v0.1.5/iacbom_0.1.5_darwin_arm64.tar.gz"
      sha256 "9fc0e3ee98adb7e3cab1f20e1741d9920814b1ec97edc7bb2a490abae074077b"

      define_method(:install) do
        bin.install "iacbom"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ojarosch/iacbom/releases/download/v0.1.5/iacbom_0.1.5_linux_amd64.tar.gz"
      sha256 "25dd0d3ef52d722b1c72ccbc2daaa430e2aebc321fc78a24abda3a21e04ffec8"
      define_method(:install) do
        bin.install "iacbom"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ojarosch/iacbom/releases/download/v0.1.5/iacbom_0.1.5_linux_arm64.tar.gz"
      sha256 "549101a048ad18a554ddccee870e585430fb999ee3fe9b13202d4434163030f0"
      define_method(:install) do
        bin.install "iacbom"
      end
    end
  end

  test do
    system "#{bin}/iacbom", "--version"
  end
end
