# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Iacbom < Formula
  desc "Bill of Materials for Terraform and OpenTofu repositories"
  homepage "https://github.com/ojarosch/iacbom"
  version "0.1.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ojarosch/iacbom/releases/download/v0.1.2/iacbom_0.1.2_darwin_amd64.tar.gz"
      sha256 "4fbe1bdc4ccaa2e6266d441320a605195db38164854269a87573072610436779"

      define_method(:install) do
        bin.install "iacbom"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ojarosch/iacbom/releases/download/v0.1.2/iacbom_0.1.2_darwin_arm64.tar.gz"
      sha256 "a1f14baac571fb1c6e1f6ae7a0d58a489f3b040f171d49937c1adb791c305653"

      define_method(:install) do
        bin.install "iacbom"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ojarosch/iacbom/releases/download/v0.1.2/iacbom_0.1.2_linux_amd64.tar.gz"
      sha256 "c04b1734f903789e03e09e921ff3a6b82019897547d6a6e2712cd68ccc371023"
      define_method(:install) do
        bin.install "iacbom"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ojarosch/iacbom/releases/download/v0.1.2/iacbom_0.1.2_linux_arm64.tar.gz"
      sha256 "d2e6d5b8993b35bae6e30945cd357cc818d26a2553026c870b28be131eddfa90"
      define_method(:install) do
        bin.install "iacbom"
      end
    end
  end

  test do
    system "#{bin}/iacbom", "--version"
  end
end
