# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Iacbom < Formula
  desc "Bill of Materials for Terraform and OpenTofu repositories"
  homepage "https://github.com/ojarosch/iacbom"
  version "0.1.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ojarosch/iacbom/releases/download/v0.1.3/iacbom_0.1.3_darwin_amd64.tar.gz"
      sha256 "3f7f53cb4b7c8d0e2f84862d5e2fa6a960d0c560fea3e84b46d3d55df8852374"

      define_method(:install) do
        bin.install "iacbom"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ojarosch/iacbom/releases/download/v0.1.3/iacbom_0.1.3_darwin_arm64.tar.gz"
      sha256 "c380d35ecd1cbb752de452ad68a0e70e72e3fd69514159ab76b9ea3375a73894"

      define_method(:install) do
        bin.install "iacbom"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ojarosch/iacbom/releases/download/v0.1.3/iacbom_0.1.3_linux_amd64.tar.gz"
      sha256 "9be756740c57a3a4ab4f72781e6e2e13f0d8ee08522a87193205ad04d4cad23f"
      define_method(:install) do
        bin.install "iacbom"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ojarosch/iacbom/releases/download/v0.1.3/iacbom_0.1.3_linux_arm64.tar.gz"
      sha256 "ccf71171c1885f307e95f144ff37bbf88eb84a714693dbbb4b9846bc7e31bc54"
      define_method(:install) do
        bin.install "iacbom"
      end
    end
  end

  test do
    system "#{bin}/iacbom", "--version"
  end
end
