# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Planlens < Formula
  desc "Reviewer-oriented semantic diff for Terraform/OpenTofu plans"
  homepage "https://github.com/ojarosch/planlens"
  version "0.2.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ojarosch/planlens/releases/download/v0.2.2/planlens_0.2.2_Darwin_x86_64.tar.gz"
      sha256 "ba3fe23a8bf26ea4db483717601d9155f4f065f7d364327f2f9b8b53eda4e2cf"

      define_method(:install) do
        bin.install "planlens"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ojarosch/planlens/releases/download/v0.2.2/planlens_0.2.2_Darwin_aarch64.tar.gz"
      sha256 "82b7dd90d7be3487a2600045df2b92b500ca7de0bd38a5986ceb52051db1398b"

      define_method(:install) do
        bin.install "planlens"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ojarosch/planlens/releases/download/v0.2.2/planlens_0.2.2_Linux_x86_64.tar.gz"
      sha256 "b40a9b4d15ab0857fd3f5d810edcc79cebaf43caa53754550589cdc9b03b3d8c"
      define_method(:install) do
        bin.install "planlens"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ojarosch/planlens/releases/download/v0.2.2/planlens_0.2.2_Linux_aarch64.tar.gz"
      sha256 "05e6cd701423b07aaaa9eca465605342a51195a9631c3be2c97bbbc559a3273a"
      define_method(:install) do
        bin.install "planlens"
      end
    end
  end

  test do
    system "#{bin}/planlens", "--version"
  end
end
