# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RcloneOrbit < Formula
  desc "Rclone-backed rclone orbit daemon with TUI setup"
  homepage "https://github.com/ojarosch/rclone-orbit"
  version "1.0.0"
  license "MIT"

  depends_on "fswatch" => :optional
  depends_on "rclone"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ojarosch/rclone-orbit/releases/download/v1.0.0/rclone-orbit_1.0.0_darwin_x86_64.tar.gz"
      sha256 "35979bd889088117851ddf06c74ba410abe78b91517f0d804faa3752952ab980"

      define_method(:install) do
        bin.install "rclone-orbit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ojarosch/rclone-orbit/releases/download/v1.0.0/rclone-orbit_1.0.0_darwin_arm64.tar.gz"
      sha256 "2b482eb49c57bfdaee8d5b8fefbb30d97c28ccb128637232c84c384154c86c75"

      define_method(:install) do
        bin.install "rclone-orbit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ojarosch/rclone-orbit/releases/download/v1.0.0/rclone-orbit_1.0.0_linux_x86_64.tar.gz"
      sha256 "dede49f5c7fb433333831fab39b7f1c8771c6fadb49a909b37e8a8399fefbe5b"
      define_method(:install) do
        bin.install "rclone-orbit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ojarosch/rclone-orbit/releases/download/v1.0.0/rclone-orbit_1.0.0_linux_arm64.tar.gz"
      sha256 "3c543f9f9e037596f76dce5c5c8251479373e79e1978c04b8948eb8ab1bdd9c3"
      define_method(:install) do
        bin.install "rclone-orbit"
      end
    end
  end

  test do
    system "#{bin}/rclone-orbit", "doctor"
  end
end
