# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RcloneOrbit < Formula
  desc "Rclone-backed rclone orbit daemon with TUI setup"
  homepage "https://github.com/ojarosch/rclone-orbit"
  version "1.0.3"
  license "MIT"

  depends_on "fswatch" => :optional
  depends_on "rclone"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ojarosch/rclone-orbit/releases/download/v1.0.3/rclone-orbit_1.0.3_darwin_x86_64.tar.gz"
      sha256 "93aaaf67b9f9cc52b918da1be8ab19a0c59f69dd2dec8da59c918cdf16fa5744"

      define_method(:install) do
        bin.install "rclone-orbit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ojarosch/rclone-orbit/releases/download/v1.0.3/rclone-orbit_1.0.3_darwin_arm64.tar.gz"
      sha256 "f5c6346007e32775996c982fc6c00cf2287cd5f037d99364c12dae91f3a91eaf"

      define_method(:install) do
        bin.install "rclone-orbit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ojarosch/rclone-orbit/releases/download/v1.0.3/rclone-orbit_1.0.3_linux_x86_64.tar.gz"
      sha256 "a1b1435d131b897ac1da1198dc8bb0d01634fff95c5a241c7c5619172f0fe87c"
      define_method(:install) do
        bin.install "rclone-orbit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ojarosch/rclone-orbit/releases/download/v1.0.3/rclone-orbit_1.0.3_linux_arm64.tar.gz"
      sha256 "da74170e36a345c9483e506e6f63208545e42d27ad560eb9b2b968b72df63057"
      define_method(:install) do
        bin.install "rclone-orbit"
      end
    end
  end

  test do
    system "#{bin}/rclone-orbit", "doctor"
  end
end
