# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfdoctor < Formula
  desc "Check the engineering hygiene of a Terraform/OpenTofu repository"
  homepage "https://github.com/ojarosch/tfdoctor"
  version "0.1.4"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ojarosch/tfdoctor/releases/download/v0.1.4/tfdoctor_0.1.4_darwin_amd64.tar.gz"
      sha256 "5fe8c2a1ba32c6234974055150a08dc1bffe7a16c0d5d02024da776a0d24070b"

      define_method(:install) do
        bin.install "tfdoctor"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ojarosch/tfdoctor/releases/download/v0.1.4/tfdoctor_0.1.4_darwin_arm64.tar.gz"
      sha256 "84011de94c6bcf78abb7752998d2452e559104ec82618cdda2e3117a633df860"

      define_method(:install) do
        bin.install "tfdoctor"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ojarosch/tfdoctor/releases/download/v0.1.4/tfdoctor_0.1.4_linux_amd64.tar.gz"
      sha256 "fd5e0854b0354ea0cc45f454f6464187a7a3855efec0955d71cb8b75de5079d9"
      define_method(:install) do
        bin.install "tfdoctor"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ojarosch/tfdoctor/releases/download/v0.1.4/tfdoctor_0.1.4_linux_arm64.tar.gz"
      sha256 "0bb27fc0610fb3585635b92b012b2af640ac90c2fb10b904bc13c4ee4b4d53f6"
      define_method(:install) do
        bin.install "tfdoctor"
      end
    end
  end

  test do
    system "#{bin}/tfdoctor", "--version"
  end
end
