# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfdoctor < Formula
  desc "Check the engineering hygiene of a Terraform/OpenTofu repository"
  homepage "https://github.com/ojarosch/tfdoctor"
  version "0.1.5"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ojarosch/tfdoctor/releases/download/v0.1.5/tfdoctor_0.1.5_darwin_amd64.tar.gz"
      sha256 "ec6fcc04ac64ad1be40fae8816465df070fa4fcff61750397f030fe6b60080a7"

      define_method(:install) do
        bin.install "tfdoctor"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ojarosch/tfdoctor/releases/download/v0.1.5/tfdoctor_0.1.5_darwin_arm64.tar.gz"
      sha256 "9e220d44280f54b63a6ba5325e41cfb36b1416e4f235ced5003ccaf820acbe29"

      define_method(:install) do
        bin.install "tfdoctor"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ojarosch/tfdoctor/releases/download/v0.1.5/tfdoctor_0.1.5_linux_amd64.tar.gz"
      sha256 "65f37919a01a975f03137eb7b7b80fc566bb571e2e44515c5c62d4f07086c312"
      define_method(:install) do
        bin.install "tfdoctor"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ojarosch/tfdoctor/releases/download/v0.1.5/tfdoctor_0.1.5_linux_arm64.tar.gz"
      sha256 "6e89d798a34c332d1c1bd8050a8337b13a140ec3045d082b3ffd95fa3d5b6ddd"
      define_method(:install) do
        bin.install "tfdoctor"
      end
    end
  end

  test do
    system "#{bin}/tfdoctor", "--version"
  end
end
