# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfdoctor < Formula
  desc "Check the engineering hygiene of a Terraform/OpenTofu repository"
  homepage "https://github.com/ojarosch/tfdoctor"
  version "0.1.7"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ojarosch/tfdoctor/releases/download/v0.1.7/tfdoctor_0.1.7_darwin_amd64.tar.gz"
      sha256 "9132a5896bef9ffb3f14f86b4884da56fa476c22c47980141bddb2f0011f2fb8"

      define_method(:install) do
        bin.install "tfdoctor"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ojarosch/tfdoctor/releases/download/v0.1.7/tfdoctor_0.1.7_darwin_arm64.tar.gz"
      sha256 "87b5fb77357ad5796771afee640177cd862c946143aaa2f271f982f410c2bd2e"

      define_method(:install) do
        bin.install "tfdoctor"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ojarosch/tfdoctor/releases/download/v0.1.7/tfdoctor_0.1.7_linux_amd64.tar.gz"
      sha256 "41b0e0654f9526c6f982e42a2c21de7745385cf6a8ae5f4353256a2524aa6043"
      define_method(:install) do
        bin.install "tfdoctor"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ojarosch/tfdoctor/releases/download/v0.1.7/tfdoctor_0.1.7_linux_arm64.tar.gz"
      sha256 "2bc1b0fb5137b0b95f6b1f96bcd7638542ad87d89b7d07d2bd05b669e479eb14"
      define_method(:install) do
        bin.install "tfdoctor"
      end
    end
  end

  test do
    system "#{bin}/tfdoctor", "--version"
  end
end
